spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic:
      name: "library-topic"
    consumer:
      bootstrap-server: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      groupId: library-events-listener-group
  datasource:
    url: jdbc:h2:mem:library-db
    driver-class-name: org.h2.Driver
    username: postgres
    password: password
    jpa:
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
  h2:
    console:
      enabled: true

